(package! codeium :recipe (:host github :repo "Exafunction/codeium.el"))
(package! nose)
(package! pytest)
(package! pyimport)
(package! py-isort)
(package! python-black)
(package! virtualenvwrapper)
(package! org-fragtog)
(package! org-auto-tangle)
(package! org-modern)
(package! cape)
(package! corfu)
(package! auctex)
(package! company-math)
(package! org-download)
(package! pandoc)
(package! ox-pandoc)
(package! lsp-tailwindcss)
